[2025-06-16 10:27:14,261] [ __main__.structured] [[91mERROR   [0m] {"@timestamp": "2025-06-16T02:27:14.260606Z", "level": "ERROR", "message": "支付处理失败", "service": "payment-service", "environment": "development", "logger": "__main__.structured", "trace_id": "8c4eae99", "request_id": "req_1750040833", "operation": "异常支付流程", "user_id": "user_123456", "amount": 15000.0, "reason": "amount_exceeded", "error_type": "ValueError", "error_message": "支付金额过大: 15000.0", "traceback": "NoneType: None\n"} | PID:37639 | Thread:8414234688
[2025-06-16 10:27:14,261] [perf.__main__.process_payment] [[91mERROR   [0m] 💥 执行失败: process_payment(3 args, 0 kwargs) 耗时 306.71ms 错误: 支付金额过大: 15000.0 | PID:37639 | Thread:8414234688
